# Generated by Django 5.0 on 2023-12-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_alter_orders_status_alter_orders_type_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.users'),
        ),
    ]
