# Generated by Django 5.0 on 2023-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_items_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
