# Generated by Django 5.0 on 2023-12-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartitem_image_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('manager', 'Manager'), ('pokup', 'Pokup')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
