# Generated by Django 5.0 on 2023-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_cart',
            field=models.IntegerField(null=True),
        ),
    ]
