# Generated by Django 5.0 on 2023-12-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orders_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
